kind: pipeline
type: docker
name: deploy

workspace:
  path: /app/rest_api_example

steps:
  - name: deploy
    image: docker/compose
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock
      - name: app_path
        path: /app
    environment:
      RAILS_ENV: production
    commands:
      - docker-compose -f docker-compose.yml up --build -d

volumes:
  - name: docker_socket
    host: 
      path: /var/run/docker.sock
  - name: app_path
    host:
      path: /app/rest_api_example

