version: "3"
services:
  db:
    image: postgres:13.0
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  bni-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rest_api_example
    volumes:
      - .:/app/rest_api_example
    ports:
      - "3002:3002"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password

    depends_on:
      - db
        # command: sleep infinity
    command: >
      /bin/sh -c "set -e
                  bundle exec rails db:setup
                  bundle exec rails db:migrate
                  bundle exec rails s -b 0.0.0.0 -p 3002"


volumes:
  db-data:

